Dashboard behaviour when deleting a saved query used within an dashboard template	"Experienced behaviour: When deleting a saved query which is used within a dashboard template this results in the standard exception ""Es ist ein Fehler aufgetreten..."" (when trying to access a dashboard instance based on the template).
Expected behaviour: Dashboard is still loading and displayed (Headline, Text and working diagrams) and only the missing diagram (due to deleted saved query) isn't displayed (or replaced by an error placeholder). "		Bug	iteraplan PO	04/Jul/13 10:56 AM	09/Jul/13 10:30 AM					dashboard									08/Jul/13 2:11 PM;sry;Please update the issue description to the actual problem!	"09/Jul/13 10:23 AM;bra;(x) unfortunately does not work. It still throws an exception if one tries to delete a query used by a CustomDashboardInstance:

{code}
Caused by: org.springframework.dao.DataIntegrityViolationException: could not delete: [de.iteratec.iteraplan.model.queries.SavedQuery#32]; SQL [/* delete de.iteratec.iteraplan.model.queries.SavedQuery */ delete from SAVED_QUERIES where ID=? and VERSION=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not delete: [de.iteratec.iteraplan.model.queries.SavedQuery#32]
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:643)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:793)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:664)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at $Proxy106.deleteSavedQuery(Unknown Source)
	at de.iteratec.iteraplan.presentation.dialog.ReportBaseFrontendServiceImpl.deleteSavedQuery(ReportBaseFrontendServiceImpl.java:436)

...


Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`iteraplan`.`dashb_inst`, CONSTRAINT `FK8DA16235FC398C9D` FOREIGN KEY (`ID`) REFERENCES `saved_queries` (`ID`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:2711)

{code}"	"09/Jul/13 10:30 AM;bra;ok, now i get the point...
saved query in the description of this ticket means a saved graphical report...

(/) that one works. I'll create another ticket regarding the above mentioned issue"	09/Jul/13 10:37 AM;bra;created ITERAPLAN-1726 adressing the above mentioned issue																																																			
